version: "3"
services:
    mongodb:
        image: mongo:7.0-jammy
        ports:
            - "27017:27017"
        volumes:
            - catalog:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
        ports:
            - "2181:2181"
    kafka:
        image: confluentinc/cp-kafka:latest
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENERS: "PLAINTEXT://localhost:9092"
            # KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
volumes:
    catalog:
