version: "3"
services:
    mongodb:
        image: mongo:7.0-jammy
        ports:
            - "27017:27017"
        volumes:
            - catalog:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
volumes:
    db:
